services:
  matrix:
    image: matrixdotorg/synapse:v1.107.0
    user: '1000'
    environment:
      SYNAPSE_HTTP_PORT: 8008
      SYNAPSE_LOG_LEVEL: 'info'
    ports:
      - 8008:8008
    profiles:
      - matrix
    volumes:
    - ./media/:/media
    - ./data/:/data
